### ISSUE TITLE
功能建议：双排网速

### ISSUE THREAD

**Issue by wuchjun** [Simplicity-Team/SimplicityTools#10]
网速改成双行显示，数字和单位换行，更省空间，看着也舒服，其他厂家基本都改了，就MIUI万年不动这个

**Comment by troublewind** [comment]
这个是，不懂MIUI为什么毫不在意状态栏的美观，臃肿图标一大堆还阉割原生的自定义隐藏系统图标，居中挖孔还网速左移，这么恶心独一家…不过别家那种双行网速用模块应该改不出来，能像chimi那种双行就好了

**Comment by Vstory** [comment]
CustoMIUIzer 网速样式，更加美观。

**Comment by winsmker** [comment]
希望加个隐藏WiFi和数据小箭头的开关，还有就是时间样式改了之后大小不能调，感觉太小了

**Comment by LittleTurtle2333** [comment]
1.4.9已适配
