### ISSUE TITLE
disable signature verification it's not working

### ISSUE THREAD

**Issue by zkollz** [Simplicity-Team/SimplicityTools#110]
**描述一下BUG情况**
清晰明了的描述BUG的情况

**如何复现**
复现的步骤
1. 去  '...'
2. 点击  '....'
3. 滚动到  '....'
4. 问题出现

**截图**
如果可以，请添加截图以帮助解释您的问题。

**手机信息：** disabled signature verification no working
 - 设备型号：Poco F3
 - MIUI版本：13 by Xiaomi Eu
 - Android版本：12

**附加信息**
在此处添加有关此问题的任何其他内容。

**Comment by LittleTurtle2333** [comment]
I don't know how to solve it.I reference [CorePatch](https://github.com/LSPosed/CorePatch). You can try it. If it can, it is my problem.

**Comment by LittleTurtle2333** [comment]
> hi, i have same phone, same xiaomi.eu miui 13, android 12 as the OP. tried latest corepatch and it's working, but i had to enable two additional options in the corepatch settings: Use installed signatures and Enhanced mode. hope this helps somewhat.

I deleted those two functions, I'll add them back next time

**Comment by LittleTurtle2333** [comment]
fixed

**Comment by zkollz** [comment]
Thanks for reply
