### ISSUE TITLE
[BUG] Hide network speed (/s) unit in Thai language can't hide.

### ISSUE THREAD

**Issue by backzaa** [Simplicity-Team/SimplicityTools#115]
Hide network speed don't work with Thai language. But can hide in English.
![IMG_20220327_171052](https://user-images.githubusercontent.com/36920655/160277285-f0ee9fa9-93d0-42bf-8aa2-bb201f55078b.jpg)

**Comment by LittleTurtle2333** [comment]
Can you send the text to me? I can't input it

**Comment by backzaa** [comment]
วิ

Thank you. 😀

**Comment by LittleTurtle2333** [comment]
fixed
