### ISSUE TITLE
[BUG] skip 5/10 seconds warning time doesn't work

### ISSUE THREAD

**Issue by skirol** [Simplicity-Team/SimplicityTools#123]
**描述一下BUG情况**
skip 5/10 seconds warning time option doesn't work. the warning window is still showing in all situations that require it.

**手机信息：**
 - 设备型号：Poco F3
 - MIUI版本：Miui 13 xiaomi.eu weekly rom (23.3.22)
 - Android版本：Android 12

**Comment by LittleTurtle2333** [comment]
What language is your phone system

**Comment by skirol** [comment]
english (us)

**Comment by LittleTurtle2333** [comment]
I have no problem here, check your scope.

**Comment by LittleTurtle2333** [comment]
Can you extract eu's secuity manager for me to try?

**Comment by skirol** [comment]
> I have no problem here, check your scope.

all recommended apps are checked.


> Can you extract eu's secuity manager for me to try?

i can. where do i send it tho?

**Comment by LittleTurtle2333** [comment]
Google drive is ok

**Comment by skirol** [comment]
here's the link for the app
https://drive.google.com/file/d/1uLKf8VTk8URkSXBeydm-KBko4nyaqf5B/view

**Comment by LittleTurtle2333** [comment]
![Video_20220403_043338_713.gif](https://user-images.githubusercontent.com/32336368/161400278-9e99e28f-9daf-4c8a-a231-deca5e727810.gif)

everything is ok

**Comment by LittleTurtle2333** [comment]
the problem is not with me
