### ISSUE TITLE
Hiding the volte icon

### ISSUE THREAD

**Issue by furopi** [Simplicity-Team/SimplicityTools#126]
Since there are already several options to hide status bar icons, my question would be if it would be possibly to add an option to hide the ugly volte icon in the status bar.

I tried nearly every option and none did work, so I'd ve very grateful if someone could add this functionality.

Thank you and kind regards from Germany,
Florian

**Comment by LittleTurtle2333** [comment]
VoLTE=HD，you can try open hide small hd icon and big hd icon

**Comment by furopi** [comment]
Ah, sorry for my misunderstanding, you're software is great, I love it! Will try instantly. You made my day, I was so annoyed by this icon...
