### ISSUE TITLE
[Feature]居中单孔手机的网速挪到右边的功能

### ISSUE THREAD

**Issue by TushningJJ** [Simplicity-Team/SimplicityTools#129]
redmi k50 稳定版的网速默认是在左边的，希望能开关放到右边去

![Screenshot_2022-04-03-20-07-38-348_com miui home](https://user-images.githubusercontent.com/9523144/161427557-538a3ce0-05cd-465e-b9f9-bfd9090bdd7f.jpg)

**Comment by LittleTurtle2333** [comment]
1.6.7 已支持。 你可以把状态栏布局兼容模式设置成中间挖孔
