### ISSUE TITLE
[Feature] Add support for 24h clock for clock related tweaks

### ISSUE THREAD

**Issue by DerivativeOfLog7** [Simplicity-Team/SimplicityTools#137]
Add support for 0-23h clocks, for both the custom clock and the lock menu "show clock with seconds"

**Comment by LittleTurtle2333** [comment]
Always support 24 hours

**Comment by DerivativeOfLog7** [comment]
![IMG_20220412_133226.jpg](https://user-images.githubusercontent.com/100133857/162951151-5f8a52f2-d316-49fc-b2e2-14b380147bb2.jpg)
![IMG_20220412_133043.jpg](https://user-images.githubusercontent.com/100133857/162951164-f1c1124b-4bb2-4b2c-a250-0ee560420509.jpg)

It's currently 1:29 PM, both of these should show 13:29 is 24h were supported; if a toggle for 24h exists already I can't seem to find it

**Comment by DerivativeOfLog7** [comment]
@LittleTurtle2333 I found the issue - if the time locale is set to auto, ST will always show 12h even when the locale uses 24h. Setting the time locale to always 24h fixes the issue.
