### ISSUE TITLE
后面会不会考虑加入自定义控制中心的功能呢？

### ISSUE THREAD

**Issue by tonynesss** [Simplicity-Team/SimplicityTools#22]
目前自己能想到的一些自定义功能
1、修改磁贴的行列数
2、隐藏磁贴文字
3、隐藏下方妙享、秒播组件
...
![Screenshot_2022-02-28-18-50-45-959_com.coolapk.market.jpg](https://user-images.githubusercontent.com/32998682/155979948-39b779a9-a3f4-441e-8770-79d5715b28c9.jpg)

**Comment by LittleTurtle2333** [comment]
新版控制中心无法操作
