### ISSUE TITLE
[BUG] 将状态栏网速的双排大小调成9，会显示异常

### ISSUE THREAD

**Issue by zkzmba793** [Simplicity-Team/SimplicityTools#98]
**描述一下BUG情况**
将状态栏网络速度的 双排大小 调到9，会出现截图内的这种情况

**截图**
![Screenshot_2022-03-20-18-09-04-097_com lt2333 simplicitytools](https://user-images.githubusercontent.com/73212412/159158167-0374b8c9-c8a5-4f55-9df7-f0743d81f2e8.jpg)
![Screenshot_2022-03-20-18-11-20-678_com android settings](https://user-images.githubusercontent.com/73212412/159158170-72cb62ec-0faf-4848-9f1a-7c336f1fdac0.jpg)

**手机信息：**
 - 设备型号：K40
 - MIUI版本：13.0.3 稳定版
 - Android版本：12

**Comment by LittleTurtle2333** [comment]
不规范的字体设计造成的，不在处理范围

**Comment by zkzmba793** [comment]
我用的是miui系统默认的misans字体，所以这是misans字体的问题吗？
