### ISSUE TITLE
[Feature] 双排网速相关功能请求

### ISSUE THREAD

**Issue by zkzmba793** [Simplicity-Team/SimplicityTools#99]
请清晰明了地讲述您的建议

请问作者如果有办法的话，能不能可以添加以下这两个功能？
1. 出一个选项把双排网速里“KB”的“B”去掉，就像以前的chimi一样
2. 将双排网速的字体换成粗体

**Comment by zkzmba793** [comment]
补一张以前的截图
![Uploading Screenshot_2021-05-31-20-28-16-753_com.miui.securitycenter.jpg…]()

**Comment by zkzmba793** [comment]
补一张以前用chimi双排网速的截图
![Screenshot_2021-05-31-20-28-16-753_com miui securitycenter](https://user-images.githubusercontent.com/73212412/159158465-187df40d-ba18-4972-b7ef-17668d721d5e.jpg)

**Comment by LittleTurtle2333** [comment]
已适配主题接口
